[project]
name = "ik-rl"
version = "0.1.0"
description = "RL environment for solving inverse kinematics for a robot arm with n many joints in 2D"
authors = [{ name = "Robin Uhrich", email = "robin.uhrich@gmail.com" }]
urls = { github = "https://github.com/RobinU434/IK-RL" }
license = { file = "LICENSE" }
keywords = [
    "reinforcement-learning",
    "robotics",
    "inverse-kinematics",
    "scaleable",
    "reinforcement-learning-environments",
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (>=2.2.3,<3.0.0)",
    "gymnasium (>=1.1.1,<2.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
flake8 = "^7.1.2"
black = "^25.1.0"
coverage = "^7.6.12"
